/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, Image } from "@react-three/drei";
import { Glitch, EffectComposer } from "@react-three/postprocessing";
import { useTexture } from "@react-three/drei";
import * as THREE from "three";
export function Model(props) {
  const imageTexture = useTexture({ map: "./person.jpg" });

  if (imageTexture) {
    const texture = imageTexture.map;

    texture.wrapS = texture.wrapT = THREE.RepeatWrapping;
    texture.flipY = false;
  }

  const { nodes, materials } = useGLTF("./models/iphone.glb");
  return (
    <React.Suspense fallback={null}>
      <group {...props} dispose={null}>
        <group
          position={[-0.24, 3.82, -0.46]}
          rotation={[Math.PI, 0, Math.PI / 2]}
          scale={[0.27, 0.02, 0.27]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder012.geometry}
            material={materials["Material.004"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder012_1.geometry}
            material={materials["Material.006"]}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder006.geometry}
          material={materials["Material.021"]}
          position={[0.27, 2.05, -0.36]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[0.08, 0.11, 0.08]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder005.geometry}
          material={materials["Material.019"]}
          position={[-0.03, -5.84, -0.57]}
          rotation={[0, 0.93, 0]}
          scale={[0.06, 0.01, 0.06]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder004.geometry}
          material={materials["Material.019"]}
          position={[-0.01, -5.84, -1.5]}
          scale={[0.06, 0.01, 0.06]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube008.geometry}
          material={materials["Material.018"]}
          position={[0, -5.69, -1.04]}
          scale={[0.15, 0.15, 0.33]}
        />
        <group
          position={[0.28, 3.45, -0.36]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[0.18, 0.04, 0.18]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder003_1.geometry}
            material={materials["Material.013"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder003_2.geometry}
            material={materials["Material.014"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder003_3.geometry}
            material={materials["Material.015"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder003_4.geometry}
            material={materials["Material.016"]}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube007.geometry}
          material={nodes.Cube007.material}
          position={[0.72, -0.82, -1.14]}
          scale={0.32}
        />
        <group
          position={[0.31, 3.26, 0.54]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[0.42, 0.03, 0.42]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder002_1.geometry}
            material={materials["Material.003"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder002_2.geometry}
            material={materials["Material.002"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder002_3.geometry}
            material={materials["Material.004"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder002_4.geometry}
            material={materials["Material.005"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder002_5.geometry}
            material={materials["Material.006"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder002_6.geometry}
            material={materials["Material.007"]}
          />
        </group>
        <group
          position={[0.31, 2.23, 0.54]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[0.42, 0.03, 0.42]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder001_1.geometry}
            material={materials["Material.003"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder001_2.geometry}
            material={materials["Material.002"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder001_3.geometry}
            material={materials["Material.004"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder001_4.geometry}
            material={materials["Material.005"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder001_5.geometry}
            material={materials["Material.006"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder001_6.geometry}
            material={materials["Material.007"]}
          />
        </group>
        {/* camera */}
        <group
          position={[0.31, 2.75, -0.37]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[0.42, 0.03, 0.42]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder_1.geometry}
            material={materials["Material.003"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder_2.geometry}
            material={materials["Material.002"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder_3.geometry}
            material={materials["Material.004"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder_4.geometry}
            material={materials["Material.005"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder_5.geometry}
            material={materials["Material.006"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder_6.geometry}
            material={materials["Material.007"]}
          />
        </group>
        {/* camera glass*/}
        <group position={[0.31, 2.75, 0.09]} scale={[0.07, 1, 1]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube006_1.geometry}
            material={materials["Material.001"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube006_2.geometry}
            material={materials["Material.008"]}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004.geometry}
          material={materials["Material.008"]}
          position={[-0.01, 2.41, -3.54]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={[0.05, 0.06, 0.17]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003.geometry}
          material={materials["Material.008"]}
          position={[-0.01, 1.52, -3.54]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={[0.06, 0.11, 0.17]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube002.geometry}
          material={materials["Material.008"]}
          position={[-0.01, 0.59, -3.54]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={[0.07, 0.11, 0.17]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001.geometry}
          material={materials["Material.008"]}
          position={[-0.01, 1.08, 1.34]}
          scale={[0.08, 0.17, 0.17]}
        />
        <group
          position={[0, 0, -1.11]}
          rotation={[-Math.PI, 0, 0]}
          scale={[-0.24, -2.31, -2.31]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_1.geometry}
            material={materials["Material.008"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_2.geometry}
            material={materials["Material.010"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_3.geometry}
            material={materials["Material.017"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_4.geometry}
            material={materials["Material.020"]}
          />
          {/* screen */}
          <EffectComposer>
            <Glitch />
          </EffectComposer>
          <mesh geometry={nodes.Cube_5.geometry}>
            <meshStandardMaterial {...imageTexture} />
          </mesh>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_6.geometry}
            material={materials["Material.023"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_7.geometry}
            material={materials["Material.024"]}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube006.geometry}
          material={materials["Material.009"]}
          position={[0.21, -0.73, -1.12]}
          scale={[0.09, 0.32, 0.32]}
        />
      </group>
    </React.Suspense>
  );
}

useGLTF.preload("/iphone.glb");
